### ISSUE TITLE
Thumbnail urls are generated with http instead of https

### ISSUE THREAD

**Issue by boerniee** [unmade/shelf-back#113]
Hello :)

the urls for the thumbnails in the list_folder method are currently generated with http scheme when using a reverse proxy.
In my setup I am using Traefik as a ssl terminating reverse proxy. As request header the 'X-Forward-Proto' header is added.
I would expect the url_for method to generate the url with the https scheme if this header is set correctly.

https://github.com/unmade/shelf-back/blob/master/app/api/files/schemas.py#L81

**Comment by unmade** [comment]
Hey, @boerniee 

I've actually had the same problem and it is because of gunicorn/uvicorn setup. To solve it you need to configure [`FORWARDED_ALLOW_IPS`](https://docs.gunicorn.org/en/stable/settings.html#forwarded-allow-ips). As per the docs:

> If you are running Nginx on a different host than Gunicorn you need to tell Gunicorn to trust the X-Forwarded-* headers sent by Nginx. By default, Gunicorn will only trust these headers if the connection comes from localhost. This is to prevent a malicious client from forging these headers

You can find more on that [here](https://docs.gunicorn.org/en/stable/deploy.html)

You can even set `FORWARDED_ALLOW_IPS=*` if no-one other than reverse proxy can connect to gunicorn

**Comment by boerniee** [comment]
Hey,
it worked! Thank you very much.
Maybe it is worth adding this as a hint to your documentation?

I really like this project and look forward for upcoming changes!
