### ISSUE TITLE
Docker Image Error

### ISSUE THREAD

**Issue by BotVue** [unmade/shelf-back#135]
When I run "docker build . -t shelf_back:0.1.0 --build-arg app_version=0.1.0" I keep getting the error message below.

Traceback (most recent call last):
  File "/usr/src/shelf-back/manage.py", line 9, in <module>
    from app import actions, crud, db, errors
  File "/usr/src/shelf-back/app/actions.py", line 16, in <module>
    from app import config, crud, errors, hashes, mediatypes, metadata, taskgroups
  File "/usr/src/shelf-back/app/config.py", line 60, in <module>
    APP_SECRET_KEY = os.environ["APP_SECRET_KEY"]
                     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'APP_SECRET_KEY'

**Comment by unmade** [comment]
Hey, @BotVue 

Are you sure this is happening while running `docker build` and not while during `docker run`?

I ran `docker build` without setting any env and it worked fine

**Comment by unmade** [comment]
You see, the problem is that during `docker build` that code should not be executed at all. 

Can you please provide a bit more context, like what setup do you have, like what platform for example (x86_64 or arm64)? Did you change/delete anything in the repo? Are you just trying to build image or maybe you have some kind of docker compose?

That's all would be very useful

**Comment by unmade** [comment]
Thank you for describing your setup. I guess the `docker build` command run without errors on Mac, but it fails on VPS server. I took a look at `caprover` documentation and I must say that project will not work as is. Simply downloading a tar file is not enough. You also have to setup environment variables, database and redis for that project to work correctly. Setting up the database is the most tricky part, because currently only EdgeDB is supported and I doubt it is provided by any hosting.

You might want to take a look at [shelf-showcase](https://github.com/unmade/shelf-showcase) and try run `docker-compose` if it is possible in `caprover`
